---
controller_projects_all:
  - name: config_as_code
    description: config as code project
    organization: config_as_code
    scm_type: git
    scm_url: git@github.com:djdanielsson/casc_demo.git
    scm_branch: "{{ scm_branch }}"
    scm_clean: true
    scm_update_on_launch: false
    scm_credential: "github"
    update_project: true
    wait: true
...
